export const normalizeCodexConfig = (config = {}) => ({
  ...config,
  type: 'native-codex-oauth',
  oauth_provider: config.oauth_provider ?? 'openai-codex',
  oauth_client_id: config.oauth_client_id ?? 'app_EMoamEEZ73f0CkXaXp7hrann',
  oauth_redirect_uri: config.oauth_redirect_uri ?? 'http://localhost:1455/auth/callback',
  authorization_endpoint: config.authorization_endpoint ?? 'https://auth.openai.com/oauth/authorize',
  token_endpoint: config.token_endpoint ?? 'https://auth0.openai.com/oauth/token',
  oauth_scope: config.oauth_scope ?? 'openid profile email offline_access api.connectors.read api.connectors.invoke',
  transport: config.transport ?? 'codex-cli',
  api_base_url: config.api_base_url ?? 'https://api.openai.com/v1',
  api_key: config.api_key ?? null,
  api_key_env: config.api_key_env ?? null,
  model: config.model ?? 'gpt-5.4',
  default_model: config.default_model ?? config.model ?? 'gpt-5.4',
  available_models: config.available_models ?? [],
  model_aliases: config.model_aliases ?? {},
  task_model_preferences: config.task_model_preferences ?? {},
  token_store: config.token_store ?? '~/.codex/auth.json',
  models_cache: config.models_cache ?? '~/.codex/models_cache.json',
  codex_cli_command: config.codex_cli_command ?? 'codex',
  codex_sandbox_mode: config.codex_sandbox_mode ?? 'read-only',
  codex_profile: config.codex_profile ?? null,
  codex_env: config.codex_env ?? {},
  workdir: config.workdir ?? null,
  timeout_ms: Number.isFinite(config.timeout_ms) ? Number(config.timeout_ms) : 120000,
  default_headers: config.default_headers ?? {}
});
