export const normalizeAnthropicConfig = (config = {}) => ({
  ...config,
  type: 'native-anthropic',
  oauth_provider: config.oauth_provider ?? 'anthropic',
  oauth_client_id: config.oauth_client_id ?? '9d1c250a-e61b-44d9-88ed-5944d1962f5e',
  oauth_redirect_uri: config.oauth_redirect_uri ?? 'https://console.anthropic.com/oauth/code/callback',
  authorization_endpoint: config.authorization_endpoint ?? 'https://console.anthropic.com/oauth/authorize',
  token_endpoint: config.token_endpoint ?? 'https://console.anthropic.com/v1/oauth/token',
  oauth_scope: config.oauth_scope ?? 'org:create_api_key user:profile user:inference',
  api_key_creation_endpoint: config.api_key_creation_endpoint ?? 'https://api.anthropic.com/api/oauth/claude_cli/create_api_key',
  api_base_url: config.api_base_url ?? 'https://api.anthropic.com',
  api_version: config.api_version ?? '2023-06-01',
  token_store: config.token_store ?? '~/.claude/oauth-store.json',
  api_key: config.api_key ?? null,
  api_key_env: config.api_key_env ?? null,
  model: config.model ?? 'claude-3-7-sonnet-latest',
  default_model: config.default_model ?? config.model ?? 'claude-3-7-sonnet-latest',
  available_models: config.available_models ?? [],
  model_aliases: config.model_aliases ?? {},
  task_model_preferences: config.task_model_preferences ?? {},
  timeout_ms: Number.isFinite(config.timeout_ms) ? Number(config.timeout_ms) : 120000,
  max_tokens: Number.isFinite(config.max_tokens) ? Number(config.max_tokens) : 4096,
  default_headers: config.default_headers ?? {}
});
